name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check-size-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check size
        run: |
          df -h

  check-size-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Check size
        run: |
          df -h

  check-size-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - name: Check size
        run: |
          df -h

  check-size-ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
      - name: Check size
        run: |
          df -h

  check-size-windows:
    runs-on: windows-2019
    steps:
      - name: Check size
        run: |
          fsutil volume diskfree c:
